Update build-wallet.yaml

diff --git a/.github/workflows/build-wallet.yaml b/.github/workflows/build-wallet.yaml
--- a/.github/workflows/build-wallet.yaml
+++ b/.github/workflows/build-wallet.yaml
@@ -27,6 +27,7 @@ jobs:
 
     - name: Install build dependencies
       run: |
+        sudo dpkg --add-architecture arm64
         sudo apt update
         sudo apt install -y \
           git curl build-essential libtool autotools-dev automake \
@@ -61,10 +62,15 @@ jobs:
         cd depends
         make -j$(nproc) HOST=$HOST
 
+    - name: Verify GMP and other depends outputs
+      run: |
+        echo "Checking for GMP in depends output..."
+        find depends/${HOST} -name 'gmp*' || echo "GMP not found in depends output"
+
     - name: Autogen and configure (release)
       run: |
         ./autogen.sh
-        ./configure --prefix=$(pwd)/depends/${HOST}
+        ./configure --prefix=`pwd`/depends/${HOST}
 
     - name: Build wallet (release)
       run: |
@@ -87,7 +93,7 @@ jobs:
       run: |
         make clean && make distclean
         ./autogen.sh
-        ./configure --prefix=$(pwd)/depends/${HOST} --disable-tests --enable-debug
+        ./configure --prefix=`pwd`/depends/${HOST} --disable-tests --enable-debug
         make -j$(nproc)
         cp src/{bitoreum-cli,bitoreumd,qt/bitoreum-qt} ~/bitoreum-build/build_debug/
 
