Version 4

diff --git a/.github/workflows/build-wallet.yaml b/.github/workflows/build-wallet.yaml
--- a/.github/workflows/build-wallet.yaml
+++ b/.github/workflows/build-wallet.yaml
@@ -443,7 +443,193 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-test-${{ needs.get-version.outputs.version }}
-          path: ${{ env.TEST_DIR }}  
+          path: ${{ env.TEST_DIR }}
+
+  build-macos-12-x86:
+
+
+    name: macOS 12 x86 Build
+
+    needs: get-version
+
+    runs-on: [self-hosted, macOS, X64, macos12]
+
+
+
+    steps:
+
+      - name: Checkout
+
+        uses: actions/checkout@v4
+
+      - name: Verify Required Packages
+
+        run: |
+
+          brew list automake libtool pkg-config miniupnpc librsvg libnatpmp zeromq python || echo "Missing brew packages"
+
+          pip3 show ds_store mac_alias || echo "Missing Python packages"
+
+      - name: Build Depends
+
+        run: |
+
+          echo "building with (($(sysctl -n hw.ncpu) - 1)) threads"
+
+          make -C depends -j$(($(sysctl -n hw.ncpu) - 1)) HOST=x86_64-apple-darwin21
+
+      - name: Configure
+
+        run: |
+
+          ./autogen.sh
+
+          ./configure --prefix=$(pwd)/depends/x86_64-apple-darwin21
+
+      - name: Build Binaries
+
+        run: |
+
+          make -j$(($(sysctl -n hw.ncpu) - 1))
+
+          mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
+
+          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}/
+
+          mv src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_not_strip/
+
+          mv src/test/test_bitoreum ${TEST_DIR}
+
+          strip ${BUILD_DIR}/*
+
+      - name: Generate Checksum and Compress
+
+        run: |
+
+          cd ${BUILD_DIR}
+
+          echo "sha256:" >> checksums.txt
+
+          echo "------------------------------------" >> checksums.txt
+
+          shasum * >> checksums.txt
+
+          echo "------------------------------------" >> checksums.txt
+
+          echo "openssl-sha256:" >> checksums.txt
+
+          echo "------------------------------------" >> checksums.txt
+
+          openssl sha256 * >> checksums.txt
+
+          cat checksums.txt
+
+          tar -cvzf ../${COIN_NAME}-macos-12-x86-${{ needs.get-version.outputs.version }}.tar.gz ../${BUILD_DIR}/*
+
+          cd ../${BUILD_DIR}_not_strip
+
+          echo "sha256:" >> checksums.txt
+
+          echo "------------------------------------" >> checksums.txt
+
+          shasum * >> checksums.txt
+
+          echo "------------------------------------" >> checksums.txt
+
+          echo "openssl-sha256:" >> checksums.txt
+
+          echo "------------------------------------" >> checksums.txt
+
+          openssl sha256 * >> checksums.txt
+
+          cat checksums.txt
+
+          tar -cvzf ../${COIN_NAME}-macos-12-x86-not_strip-${{ needs.get-version.outputs.version }}.tar.gz *
+
+          cd ..
+
+          mkdir -p ${COMPRESS_DIR}
+
+          mv *.tar.gz ${COMPRESS_DIR}/
+
+          cd ${COMPRESS_DIR}
+
+          echo "sha256: $(shasum ${COIN_NAME}-macos-12-x86-${{ needs.get-version.outputs.version }}.tar.gz)" >> checksums.txt
+
+          echo "openssl-sha256: $(openssl sha256 ${COIN_NAME}-macos-12-x86-${{ needs.get-version.outputs.version }}.tar.gz)" >> checksums.txt
+
+          echo "sha256: $(shasum ${COIN_NAME}-macos-12-x86-not_strip-${{ needs.get-version.outputs.version }}.tar.gz)" >> checksums.txt
+
+          echo "openssl-sha256: $(openssl sha256 ${COIN_NAME}-macos-12-x86-not_strip-${{ needs.get-version.outputs.version }}.tar.gz)" >> checksums.txt
+
+          cat checksums.txt
+
+          cd ..
+
+
+      - name: Upload Artifacts
+
+
+      - name: Upload Core Artifacts
+
+        uses: actions/upload-artifact@v4
+
+        with:
+
+
+          name: ${{ env.COIN_NAME }}-macos-12-x86-dmg-${{ needs.get-version.outputs.version }}
+
+
+          name: ${{ env.COIN_NAME }}-macos-12-x86-core-${{ needs.get-version.outputs.version }}
+
+          path: ${{ env.COMPRESS_DIR }}
+
+
+
+
+      - name: Upload Test Artifacts
+
+        uses: actions/upload-artifact@v4
+
+        with:
+
+
+          name: ${{ env.COIN_NAME }}-macos-12-x86-dmg-test-${{ needs.get-version.outputs.version }}
+
+
+          name: ${{ env.COIN_NAME }}-macos-12-x86-test-${{ needs.get-version.outputs.version }}
+
+          path: ${{ env.TEST_DIR }}
+
+      - name: Generate Macos dmg files
+
+        run: |
+
+          make deploy
+
+          mkdir -p macos-dmg
+
+          # Rename to your preferred name (optional) or use actual filename created
+
+          mv Bitoreum-Qt.dmg macos-dmg/Crystal-Bitoreum-Qt.dmg
+
+          cd macos-dmgMore actions
+
+          echo "sha256: $(shasum Crystal-Bitoreum-Qt.dmg)" >> checksums.txt
+
+          echo "openssl-sha256: $(openssl sha256 Crystal-Bitoreum-Qt.dmg)" >> checksums.txt
+
+          cd ..
+
+      - name: Upload dmg file
+
+        uses: actions/upload-artifact@v4
+
+        with:
+
+          name: ${{ env.COIN_NAME }}-macos-12-x86-dmg-${{ needs.get-version.outputs.version }}
+
+          path: macos-dmg
           
   build-macos-13:
     name: macOS 13 Build
@@ -475,9 +661,9 @@ jobs:
         run: |
           make -j8
           mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
-          cp src/{yerbas-cli,yerbasd,qt/yerbas-qt} ${BUILD_DIR}/
-          mv src/{yerbas-cli,yerbasd,qt/yerbas-qt} ${BUILD_DIR}_not_strip/
-          mv src/test/test_yerbas ${TEST_DIR}
+          cp src/{bitoreum-cli,bitoreumd,qt/bitoreum-qt} ${BUILD_DIR}/
+          mv src/{bitoreum-cli,bitoreumd,qt/bitoreum-qt} ${BUILD_DIR}_not_strip/
+          mv src/test/test_bitoreum ${TEST_DIR}
           strip ${BUILD_DIR}/*
 
       - name: Generate Checksum and Compress
@@ -529,10 +715,10 @@ jobs:
         run: |
           make deploy
           mkdir -p macos-dmg
-          mv Yerbas-Qt.dmg macos-dmg/
+          mv Bitoreum-Qt.dmg macos-dmg/
           cd macos-dmg
-          echo "sha256: `shasum Yerbas-Qt.dmg`" >> checksums.txt
-          echo "openssl-sha256: `openssl sha256 Yerbas-Qt.dmg`" >> checksums.txt
+          echo "sha256: `shasum Bitoreum-Qt.dmg`" >> checksums.txt
+          echo "openssl-sha256: `openssl sha256 Bitoreum-Qt.dmg`" >> checksums.txt
           cd ..
 
       - name: Upload dmg file
